services:
  app:
    image: php:8.2-fpm
    container_name: laravel-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
